/// Model representing a session frame for tracking custom user flows.
///
/// Session frames allow you to track custom user flows in your app,
/// such as checkout processes, onboarding flows, or any multi-step process.
///
/// ## Usage Example
///
/// ```dart
/// // Start a session frame for checkout process
/// final frame = await appDynamics.startSessionFrame('checkout_process');
///
/// // Perform checkout steps...
/// await performCheckout();
///
/// // End the session frame
/// await appDynamics.endSessionFrame(frame);
/// ```
class AppDynamicsSessionFrame {
  /// Unique identifier for this session frame.
  ///
  /// Generated by the AppDynamics SDK when the frame is started.
  final String id;

  /// Name of the session frame.
  ///
  /// This is the name you provided when starting the frame.
  final String name;

  /// Timestamp when the frame was started.
  final DateTime startTime;

  /// Timestamp when the frame was ended (null if still active).
  final DateTime? endTime;

  /// Duration of the frame in milliseconds (null if still active).
  final int? durationMs;

  /// Whether this frame is currently active.
  final bool isActive;

  /// Custom properties associated with this frame.
  final Map<String, dynamic>? properties;

  const AppDynamicsSessionFrame({
    required this.id,
    required this.name,
    required this.startTime,
    this.endTime,
    this.durationMs,
    required this.isActive,
    this.properties,
  });

  /// Creates a copy of this session frame with optional field updates.
  AppDynamicsSessionFrame copyWith({
    String? id,
    String? name,
    DateTime? startTime,
    DateTime? endTime,
    int? durationMs,
    bool? isActive,
    Map<String, dynamic>? properties,
  }) {
    return AppDynamicsSessionFrame(
      id: id ?? this.id,
      name: name ?? this.name,
      startTime: startTime ?? this.startTime,
      endTime: endTime ?? this.endTime,
      durationMs: durationMs ?? this.durationMs,
      isActive: isActive ?? this.isActive,
      properties: properties ?? this.properties,
    );
  }

  @override
  String toString() {
    return 'AppDynamicsSessionFrame('
        'id: $id, '
        'name: $name, '
        'isActive: $isActive, '
        'durationMs: $durationMs'
        ')';
  }
}

