/// Model representing a timer for tracking events that span multiple methods.
///
/// Timers allow you to track the duration of operations that span across
/// multiple methods or async operations.
///
/// ## Usage Example
///
/// ```dart
/// // Start a timer for data processing
/// final timer = await appDynamics.startTimer('data_processing');
///
/// // Perform processing...
/// await processData();
///
/// // Stop the timer
/// await appDynamics.stopTimer(timer);
/// ```
class AppDynamicsTimer {
  /// Unique identifier for this timer.
  ///
  /// Generated by the AppDynamics SDK when the timer is started.
  final String id;

  /// Name of the timer.
  ///
  /// This is the name you provided when starting the timer.
  final String name;

  /// Timestamp when the timer was started.
  final DateTime startTime;

  /// Timestamp when the timer was stopped (null if still running).
  final DateTime? stopTime;

  /// Duration of the timer in milliseconds (null if still running).
  final int? durationMs;

  /// Whether this timer is currently running.
  final bool isRunning;

  /// Custom properties associated with this timer.
  final Map<String, dynamic>? properties;

  const AppDynamicsTimer({
    required this.id,
    required this.name,
    required this.startTime,
    this.stopTime,
    this.durationMs,
    required this.isRunning,
    this.properties,
  });

  /// Creates a copy of this timer with optional field updates.
  AppDynamicsTimer copyWith({
    String? id,
    String? name,
    DateTime? startTime,
    DateTime? stopTime,
    int? durationMs,
    bool? isRunning,
    Map<String, dynamic>? properties,
  }) {
    return AppDynamicsTimer(
      id: id ?? this.id,
      name: name ?? this.name,
      startTime: startTime ?? this.startTime,
      stopTime: stopTime ?? this.stopTime,
      durationMs: durationMs ?? this.durationMs,
      isRunning: isRunning ?? this.isRunning,
      properties: properties ?? this.properties,
    );
  }

  @override
  String toString() {
    return 'AppDynamicsTimer('
        'id: $id, '
        'name: $name, '
        'isRunning: $isRunning, '
        'durationMs: $durationMs'
        ')';
  }
}

